### ISSUE TITLE
update master file

### ISSUE THREAD

**Issue by andybeet** [andybeet/InportXML#1]
- [x] format zip fields as text? otherwise leading zero is omitted
- [x] the drop down entries result in a leading space added to field name. Does this effect upload?
- [x] can leave keyword-type and keyword blank?
- [x] The NEFSC address is hard coded for some fields, not others. is this intentional?
- [x] Distributor support role type instructions and organization are swapped
- [x] Geographic bounds description, not clear. Do they need to enter lat long or a general descrption?
- [x] security-class instruction needs to be added
- [x] accuracy, bias, sensitivity. Are these values from a drop down or can user type anything?

**Comment by seanhardison1** [comment]
1. Fixed fields with zip
2. Fixed leading space
3. Keyword type must be associated with keyword - opening new issue for addressing empty keyword fields
4. Not intentional - fixed
5. Not intentional - fixed
6. Added geographic bounding box info (optional). Geo description is required with or w/o bounding box
7. Add instructions but not much to go off of here
8. User input

**Comment by andybeet** [comment]
closed
